In [93]:
import pandas as pd

df = pd.read_csv('store-sales-time-series-forecasting/train.csv').reset_index(drop=True)

In [94]:
df=df.drop(columns=['id','onpromotion'])
df

date  store_nbr                      family     sales
0        2013-01-01          1                  AUTOMOTIVE     0.000
1        2013-01-01          1                   BABY CARE     0.000
2        2013-01-01          1                      BEAUTY     0.000
3        2013-01-01          1                   BEVERAGES     0.000
4        2013-01-01          1                       BOOKS     0.000
...             ...        ...                         ...       ...
3000883  2017-08-15          9                     POULTRY   438.133
3000884  2017-08-15          9              PREPARED FOODS   154.553
3000885  2017-08-15          9                     PRODUCE  2419.729
3000886  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000
3000887  2017-08-15          9                     SEAFOOD    16.000

[3000888 rows x 4 columns]

In [95]:
df['nbr_family'] = df.apply(lambda x: f"{x['store_nbr']}_{x['family']}", axis=1)
df = df.drop(columns=['store_nbr','family'])
df

date     sales                    nbr_family
0        2013-01-01     0.000                  1_AUTOMOTIVE
1        2013-01-01     0.000                   1_BABY CARE
2        2013-01-01     0.000                      1_BEAUTY
3        2013-01-01     0.000                   1_BEVERAGES
4        2013-01-01     0.000                       1_BOOKS
...             ...       ...                           ...
3000883  2017-08-15   438.133                     9_POULTRY
3000884  2017-08-15   154.553              9_PREPARED FOODS
3000885  2017-08-15  2419.729                     9_PRODUCE
3000886  2017-08-15   121.000  9_SCHOOL AND OFFICE SUPPLIES
3000887  2017-08-15    16.000                     9_SEAFOOD

[3000888 rows x 3 columns]

In [4]:
df_pv = df.pivot(index='date',columns='nbr_family',values='sales').fillna(0)

In [5]:
df_pv

nbr_family  10_AUTOMOTIVE  10_BABY CARE  10_BEAUTY  10_BEVERAGES  10_BOOKS  \
date                                                                         
2013-01-01            0.0           0.0        0.0           0.0       0.0   
2013-01-02            3.0           0.0        6.0         396.0       0.0   
2013-01-03            2.0           0.0        3.0         399.0       0.0   
2013-01-04            2.0           0.0        4.0         460.0       0.0   
2013-01-05            0.0           0.0        3.0         624.0       0.0   
...                   ...           ...        ...           ...       ...   
2017-08-11            2.0           0.0        2.0        1459.0       0.0   
2017-08-12            2.0           0.0        3.0        1332.0       0.0   
2017-08-13            0.0           0.0        5.0        1526.0       0.0   
2017-08-14            1.0           0.0        6.0        1129.0       0.0   
2017-08-15            4.0           0.0        4.0        1608.0       0.0   

nbr_family  10_BREAD/BAKERY  10_CELEBRATION  10_CLEANING  10_DAIRY  10_DELI  \
date                                                                          
2013-01-01              0.0             0.0          0.0       0.0      0.0   
2013-01-02            151.0             0.0       1110.0     101.0    276.0   
2013-01-03            129.0             0.0        970.0     113.0    269.0   
2013-01-04            105.0             0.0        669.0      66.0     92.0   
2013-01-05            112.0             0.0       1093.0      88.0    194.0   
...                     ...             ...          ...       ...      ...   
2017-08-11             76.0             5.0        532.0     251.0    269.0   
2017-08-12            113.0             5.0        676.0     255.0    276.0   
2017-08-13            119.0             6.0        670.0     270.0    251.0   
2017-08-14             82.0             3.0        710.0     253.0    313.0   
2017-08-15            112.0             2.0        731.0     328.0    175.0   

nbr_family  ...  9_MAGAZINES  9_MEATS  9_PERSONAL CARE  9_PET SUPPLIES  \
date        ...                                                          
2013-01-01  ...          0.0    0.000              0.0             0.0   
2013-01-02  ...          0.0  374.531            482.0             0.0   
2013-01-03  ...          0.0  400.863            372.0             0.0   
2013-01-04  ...          0.0  310.878            324.0             0.0   
2013-01-05  ...          0.0  447.685            461.0             0.0   
...         ...          ...      ...              ...             ...   
2017-08-11  ...          5.0  309.245            373.0            11.0   
2017-08-12  ...          2.0  260.298            400.0             7.0   
2017-08-13  ...          3.0  327.206            510.0             2.0   
2017-08-14  ...         12.0  330.975            445.0             2.0   
2017-08-15  ...         11.0  449.228            522.0             6.0   

nbr_family  9_PLAYERS AND ELECTRONICS  9_POULTRY  9_PREPARED FOODS  9_PRODUCE  \
date                                                                            
2013-01-01                        0.0      0.000           0.00000      0.000   
2013-01-02                        0.0    651.292          83.00000      0.000   
2013-01-03                        0.0    509.496          66.00000      0.000   
2013-01-04                        0.0    332.672          57.00000      0.000   
2013-01-05                        0.0    510.919          84.00000      0.000   
...                               ...        ...               ...        ...   
2017-08-11                        2.0    525.224         112.10000   1453.078   
2017-08-12                       10.0    383.387         129.90399   1419.264   
2017-08-13                        9.0    412.458         105.16900   1693.607   
2017-08-14                       14.0    283.429         114.12000   1348.425   
2017-08-15            

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
tr_len = int(0.8*len(df_pv))
tr_data = df_pv.iloc[:tr_len]
te_data = df_pv.iloc[tr_len:]

tr_scale = scaler.fit_transform(tr_data)
te_scale = scaler.fit_transform(te_data)

In [69]:
tr_scale

array([[-1.20820353, -0.24226963, -1.00978177, ..., -0.9209293 ,
        -0.26986362, -1.77746243],
       [-0.08090026, -0.24226963,  3.44008533, ..., -0.9209293 ,
        -0.26986362,  1.30484299],
       [-0.45666802, -0.24226963,  1.21515178, ..., -0.9209293 ,
        -0.26986362,  0.86023304],
       ...,
       [-0.83243577, -0.24226963, -0.26813725, ...,  0.4445479 ,
         6.39609377, -0.6744837 ],
       [-0.45666802,  0.56951442,  1.21515178, ...,  1.06239222,
        16.97697853,  1.79176157],
       [-0.08090026,  1.38129847, -1.00978177, ...,  1.78421724,
         4.12120355,  2.30569015]], shape=(1347, 1782))

In [10]:
import numpy as np

def process_data(data,input_len,out_len):
    x,y = [],[]
    for i in range(len(data)-input_len-out_len+1):
        x.append(data[i:i+input_len][:])
        y.append(data[i+input_len:i+input_len+out_len][:])
    return np.array(x),np.array(y)

In [11]:
tr_x,tr_y = process_data(tr_scale,120,16)
te_x,te_y = process_data(te_scale,120,16)

In [65]:
tr_x[0:32,-1,:][0]

array([ 1.79793853, -0.24226963, -0.26813725, ..., -0.9209293 ,
       -0.26986362, -0.22322675], shape=(1782,))

In [50]:
import tensorflow as tf
from tensorflow import keras

In [54]:
#轉成 tensorflow 可以使用的張量
X_train_tensor = tf.convert_to_tensor(tr_x,dtype = tf.float32)
y_train_tensor = tf.convert_to_tensor(tr_y,dtype = tf.float32)
X_test_tensor = tf.convert_to_tensor(te_x,dtype = tf.float32)
y_test_tensor = tf.convert_to_tensor(te_y,dtype = tf.float32)
# 建立訓練集 Dataset
batch_size = 32
train_dataset = tf.data.Dataset.from_tensor_slices((tr_x, tr_y)) \
                               .shuffle(buffer_size=1000) \
                               .batch(batch_size)

# 建立測試集 Dataset
test_dataset = tf.data.Dataset.from_tensor_slices((te_x, te_y)) \
                              .batch(batch_size)

In [76]:
# 使用時序卷積神經網路 (Temporal CN)
def build_tcn_model():
    model = tf.keras.Sequential([
        # 將資料型態由 (batch_size, timesteps, feature) 轉成 (batch_size, feature), timesteps)
        tf.keras.layers.Permute((2, 1)),
        # 接受 (batch_size, feature), timesteps) 之型態，
        tf.keras.layers.Conv1D(64, kernel_size=3, padding='same', dilation_rate=1, activation='relu'),
        tf.keras.layers.Conv1D(64, kernel_size=3, padding='same', dilation_rate=2, activation='relu'),
        tf.keras.layers.Conv1D(64, kernel_size=3, padding='same', dilation_rate=4, activation='relu'),
        tf.keras.layers.Lambda(lambda x: x[:, :, -1]),  # Select the last time step
        tf.keras.layers.Dense(33 * 54 * 16),
        tf.keras.layers.Reshape((16, 33 * 54)),
    ])
    return model

# 加載模型
model = build_tcn_model()

# 編譯模型
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),  # Adam 優化器
              loss='mse',  # 損失函數為 MSE
              metrics=['mse'])  # 評估指標為 MSE

# 訓練模型
epochs = 10
model.fit(train_dataset, validation_data=test_dataset, epochs=epochs)
model.summary()

Epoch 1/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 21s 505ms/step - loss: 0.7414 - mse: 0.7414 - val_loss: 0.8158 - val_mse: 0.8158
Epoch 2/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 20s 525ms/step - loss: 0.5564 - mse: 0.5564 - val_loss: 0.8053 - val_mse: 0.8053
Epoch 3/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 19s 491ms/step - loss: 0.4728 - mse: 0.4728 - val_loss: 0.8100 - val_mse: 0.8100
Epoch 4/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 480ms/step - loss: 0.4056 - mse: 0.4056 - val_loss: 0.8284 - val_mse: 0.8284
Epoch 5/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 480ms/step - loss: 0.3454 - mse: 0.3454 - val_loss: 0.8708 - val_mse: 0.8708
Epoch 6/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 480ms/step - loss: 0.2904 - mse: 0.2904 - val_loss: 0.9089 - val_mse: 0.9089
Epoch 7/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 481ms/step - loss: 0.2479 - mse: 0.2479 - val_loss: 0.9461 - val_mse: 0.9461
Epoch 8/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 481ms/step - loss: 0.2112 - mse: 0.2112 - val_loss: 0.9839 - val_mse: 0.9839
Epoch 9/10
38/38 ━━━━━━━━━━━━━━━━━━━━ 18s 480ms/

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ permute_3 (Permute)                  │ (None, 1782, 120)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_9 (Conv1D)                    │ (None, 1782, 64)            │          23,104 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_10 (Conv1D)                   │ (None, 1782, 64)            │          12,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_11 (Conv1D)                   │ (None, 1782, 64)            │          12,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lambda_1 (Lambda)                    │ (None, 1782)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 28512)               │      50,836,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ reshape_3 (Reshape)                  │ (None, 16, 1782)            │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 152,654,114 (582.33 MB)

 Trainable params: 50,884,704 (194.11 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 101,769,410 (388.22 MB)

In [109]:
pred_scaler = scaler.fit_transform(df_pv)
pre_data = pred_scaler[-120:]

In [111]:
input_tensor = tf.convert_to_tensor(pre_data[tf.newaxis, ...], dtype=tf.float32)
print("模型輸入形狀：", input_tensor.shape)
predictions = model.predict(input_tensor)

# 查看預測結果形狀
print("預測結果形狀：", predictions.shape)
predictions = scaler.inverse_transform(predictions[0])
predictions = np.maximum(predictions, 0)

模型輸入形狀： (1, 120, 1782)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
預測結果形狀： (1, 16, 1782)


In [112]:
predictions

array([[7.3361611e-01, 1.7819393e+00, 6.8060762e-01, ..., 9.2093250e+02,
        3.6574673e+01, 1.2055493e+01],
       [1.4787009e+00, 0.0000000e+00, 2.7055597e-01, ..., 1.0013449e+03,
        6.0802658e+01, 2.3002758e+01],
       [3.5454006e+00, 7.1207446e-01, 7.7311516e-02, ..., 1.3198121e+03,
        5.5812321e+01, 2.2324068e+01],
       ...,
       [2.9366412e+00, 4.6605225e+00, 2.1835518e+00, ..., 4.4273950e+03,
        5.4474461e+01, 2.6364975e+01],
       [4.3314805e+00, 3.9703412e+00, 0.0000000e+00, ..., 3.4920562e+03,
        5.1340103e+01, 2.0453850e+01],
       [0.0000000e+00, 3.1256678e+00, 0.0000000e+00, ..., 3.3018167e+03,
        8.1402374e+01, 2.6938023e+01]], shape=(16, 1782), dtype=float32)

In [121]:

test_df = pd.read_csv('store-sales-time-series-forecasting/test.csv')
test_df['store_family'] = test_df['store_nbr'].astype(str) + '_' + test_df['family']
dates = sorted(test_df['date'].unique())
pred_df = pd.DataFrame(predictions, index=dates, columns=df_pv.columns)
pred_long = pred_df.stack().reset_index()  # opposite of pivot basically
pred_long.columns = ['date', 'store_family', 'sales']

submission = test_df.merge(pred_long, on=['date', 'store_family'], how='left')[['id', 'sales']]
submission.to_csv('submission.csv', index=False)

print("Predictions saved to submission.csv")

Predictions saved to submission.csv
